# Generated by Django 3.0.1 on 2019-12-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pid',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
