# Generated by Django 3.0.1 on 2019-12-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sid', '0003_auto_20191219_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='pid',
            field=models.CharField(default='00000000000000000000000000000000', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
