# Generated by Django 3.0.1 on 2019-12-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sid', '0004_auto_20191220_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
