# Generated by Django 3.0.1 on 2019-12-24 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_sid', '0005_auto_20191220_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchid', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('lose', 'Lose')], default='pending', max_length=7)),
                ('score', models.BigIntegerField()),
                ('playtime', models.DateTimeField()),
                ('turn_count', models.IntegerField()),
                ('spawned_alias', models.IntegerField()),
                ('killed_alias', models.IntegerField()),
                ('killed_hostiles', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('pid', models.ForeignKey(help_text='유저 테이블 외래키', on_delete=django.db.models.deletion.CASCADE, to='auth_sid.User')),
            ],
        ),
    ]
