# Generated by Django 3.0.1 on 2019-12-24 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sid', '0005_auto_20191220_0013'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pid',
            field=models.ForeignKey(db_column='pid', help_text='유저 테이블 외래키', on_delete=django.db.models.deletion.CASCADE, to='auth_sid.User'),
        ),
    ]
