# Generated by Django 3.0.1 on 2019-12-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191224_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played_as',
            field=models.CharField(choices=[('insomnia', 'Insomnia'), ('orangefamily', 'Orangefamily'), ('overhit', 'Overhit'), ('meisterboi', 'Meisterboi')], default='insomnia', max_length=12),
        ),
    ]
