# Generated by Django 3.0.1 on 2019-12-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sid', '0005_auto_20191220_0013'),
        ('api', '0003_match_played_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('objectid', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unborn', 'Unborn'), ('alive', 'Alive'), ('stun', 'Stun'), ('dead', 'Dead')], default='unborn', max_length=6)),
                ('job', models.CharField(choices=[('leader', 'Leader'), ('basic', 'Basic'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='leader', max_length=8)),
                ('hp', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('belong_to', models.ForeignKey(db_column='pid', help_text='유저 테이블 외래키', on_delete=django.db.models.deletion.CASCADE, to='auth_sid.User')),
                ('matchid', models.ForeignKey(db_column='matchid', help_text='매치 테이블 외래키', on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('actionid', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('start', 'Start'), ('spawn', 'Spawn'), ('move', 'Move'), ('attack', 'Attack'), ('moveattack', 'Moveattack'), ('die', 'Die'), ('end', 'End')], default='start', max_length=10)),
                ('destination_x', models.IntegerField(null=True)),
                ('destination_y', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('matchid', models.ForeignKey(db_column='matchid', help_text='매치 테이블 외래키', on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_origin', to='api.Object')),
                ('pid', models.ForeignKey(db_column='pid', help_text='유저 테이블 외래키', on_delete=django.db.models.deletion.CASCADE, to='auth_sid.User')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_to', to='api.Object')),
            ],
        ),
    ]
