# Generated by Django 3.0.1 on 2019-12-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_action_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='damage',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='heal',
            field=models.BigIntegerField(),
        ),
    ]
