# Generated by Django 3.0.1 on 2019-12-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191226_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.CharField(choices=[('unborn', 'Unborn'), ('alive', 'Alive'), ('stun', 'Stun'), ('dead', 'Dead'), ('done', 'Done')], default='unborn', max_length=6),
        ),
    ]
