# Generated by Django 3.0.1 on 2019-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191226_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='faction',
            field=models.CharField(choices=[('insomnia', 'Insomnia'), ('orangefamily', 'Orangefamily'), ('overhit', 'Overhit'), ('meisterboi', 'Meisterboi')], default='insomnia', max_length=12),
        ),
    ]
