# Generated by Django 3.0.1 on 2019-12-26 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_object_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='match',
            name='terminated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('spawn', 'Spawn'), ('move', 'Move'), ('attack', 'Attack'), ('moveattack', 'Moveattack'), ('die', 'Die')], default='move', max_length=10),
        ),
    ]
