# Generated by Django 3.0.1 on 2019-12-27 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sid', '0006_auto_20191226_0539'),
        ('api', '0008_auto_20191226_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='pid',
        ),
        migrations.AddField(
            model_name='match',
            name='pid1',
            field=models.ForeignKey(help_text='유저 테이블 외래키', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid1', to='auth_sid.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='pid2',
            field=models.ForeignKey(help_text='유저 테이블 외래키', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid2', to='auth_sid.User'),
        ),
    ]
