# Generated by Django 3.0.1 on 2019-12-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sid', '0006_auto_20191226_0539'),
        ('api', '0009_auto_20191227_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='pid1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='pid2',
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(db_column='player1', help_text='유저 테이블 외래키', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid1', to='auth_sid.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(db_column='player2', help_text='유저 테이블 외래키', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid2', to='auth_sid.User'),
        ),
    ]
