# Generated by Django 3.0.1 on 2019-12-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191227_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='played_as',
            new_name='played_as1',
        ),
        migrations.AddField(
            model_name='match',
            name='played_as2',
            field=models.CharField(choices=[('insomnia', 'Insomnia'), ('orangefamily', 'Orangefamily'), ('overhit', 'Overhit'), ('meisterboi', 'Meisterboi')], default='insomnia', max_length=12),
        ),
    ]
